export const newTrials = [
  { item: 1, targetWord: 'zucchini' },
  { item: 2, targetWord: 'badger' },
  { item: 3, targetWord: 'arugula' },
  { item: 4, targetWord: 'ruin' },
  { item: 5, targetWord: 'elk' },
  { item: 6, targetWord: 'gazelle' },
  { item: 7, targetWord: 'ocean' },
  { item: 8, targetWord: 'palm tree' },
  { item: 9, targetWord: 'fan' },
  { item: 10, targetWord: 'labyrinth' },
  { item: 11, targetWord: 'flounder' },
  { item: 12, targetWord: 'chanterelle' },
  { item: 13, targetWord: 'choir' },
  { item: 14, targetWord: 'jaguar' },
  { item: 15, targetWord: 'carnation' },
  { item: 16, targetWord: 'lobster' },
  { item: 17, targetWord: 'cello' },
  { item: 18, targetWord: 'kayak' },
  { item: 19, targetWord: 'satellite' },
  { item: 20, targetWord: 'orchid' },
];
